# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/macdive/schema.rs"
filter = { only_tables = ["ZDIVESITE"] }
import_types = ["diesel::sql_types::*", "crate::macdive::types::NsDate"]